// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJyX9kJmXotxCoac4heT2W2u7y5ByIrPk',
    appId: '1:809418704719:web:6dbc805e93079186a2673a',
    messagingSenderId: '809418704719',
    projectId: 'manipal-e7134',
    authDomain: 'manipal-e7134.firebaseapp.com',
    storageBucket: 'manipal-e7134.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3ZMEG5Scl5qfhsxgnnMCbZc8syPAPk7o',
    appId: '1:809418704719:android:7bf60efeba669f50a2673a',
    messagingSenderId: '809418704719',
    projectId: 'manipal-e7134',
    storageBucket: 'manipal-e7134.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEwr-SwgMngaor9oGAF8OMjvIdNL0KQNk',
    appId: '1:809418704719:ios:d8b9053c06c033a5a2673a',
    messagingSenderId: '809418704719',
    projectId: 'manipal-e7134',
    storageBucket: 'manipal-e7134.appspot.com',
    androidClientId: '809418704719-f3jkq38ulc8ullg5f5dk4d9l9kap0vbv.apps.googleusercontent.com',
    iosClientId: '809418704719-rji07q3drsjiphmn41q8l7ujtd6k89c5.apps.googleusercontent.com',
    iosBundleId: 'com.example.businessApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEwr-SwgMngaor9oGAF8OMjvIdNL0KQNk',
    appId: '1:809418704719:ios:d8b9053c06c033a5a2673a',
    messagingSenderId: '809418704719',
    projectId: 'manipal-e7134',
    storageBucket: 'manipal-e7134.appspot.com',
    androidClientId: '809418704719-f3jkq38ulc8ullg5f5dk4d9l9kap0vbv.apps.googleusercontent.com',
    iosClientId: '809418704719-rji07q3drsjiphmn41q8l7ujtd6k89c5.apps.googleusercontent.com',
    iosBundleId: 'com.example.businessApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJyX9kJmXotxCoac4heT2W2u7y5ByIrPk',
    appId: '1:809418704719:web:b0095cc4a387e493a2673a',
    messagingSenderId: '809418704719',
    projectId: 'manipal-e7134',
    authDomain: 'manipal-e7134.firebaseapp.com',
    storageBucket: 'manipal-e7134.appspot.com',
  );
}
